---
title: "Msc Thesis Figures"
author: "Valentin Lucet"
date: "17/07/2020"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 5
    toc_float:
      collapsed: true
      smooth_scroll: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages({
  library(raster)
  library(sf)
  library(tidyverse)
  library(ggplot2)
  library(gganimate)
  library(transformr)
  library(animation)
  library(rasterVis)
  library(ggmap)
  library(gifski)
  library(gtools)
  library(fmsb)
  library(RColorBrewer)
  library(scales)
  library(ggradar)
  library(tidymodels)
  library(patchwork)
})
```

### Data prep
#### Cleaning and formatting

We start by preparing the data from the outputs of scripts `7.1` and `8.1`. 

```{r data prep}
# Results dir + mun shapefile
sce_dir_vec <- list.files("libraries/stsim/monteregie-conncons-scripted.ssim.output", 
                          full.names = T)
mun <- st_read("data/mun/munic_SHP_clean.shp", quiet = TRUE)

# results key
results_clean <- read_rds("data/temp/stsim_run_results.RDS") %>% 
  dplyr::select(scenarioId, name) %>% 
  mutate(name =  gsub(.$name, pattern = " \\(.+\\)", replacement = "")) %>% 
  mutate(sce =  paste0("sce_", .$scenarioId)) %>% 
  mutate(chapter = c("none", rep("chap_1", 6), rep("chap_2", 9))) %>% 
  mutate(splitted = str_split(name, " \\| ")) %>% 
  mutate(climate = unlist(map(splitted, ~unlist(.x[2])))) %>% 
  mutate(run = unlist(map(splitted, ~unlist(.x[1])))) %>% 
  dplyr::select(-splitted) %>% 
  replace_na(list(climate = "none"))

# Final extracted datasets
df_final <- readRDS("outputs/final/final_df_current_density.RDS") %>%
  mutate(timestep = (timestep*10)+1990, source = "model")
df_final_origin <- readRDS("outputs/final/final_df_origin_current_density.RDS") %>%
  mutate(timestep = timestep*10+1990, source = "model")

# Sum all municipalities
df_summarised <- df_final %>%
  group_by(sce, timestep, species, iteration) %>% 
  summarise(sum_cur = sum(current)) %>% ungroup %>%
  mutate(source = "model")
df_origin_summarised <- df_final_origin %>%
  group_by(timestep, species) %>% 
  summarise(sum_cur = sum(mean)) %>% ungroup %>% 
  mutate(sce = "sce_0", source = "observation")

# Joined dataset
joined <- full_join(df_summarised, df_origin_summarised, 
                    by=c("sce", "source", "species", "timestep", "sum_cur")) %>% 
  left_join(results_clean, by = "sce")  %>% 
  replace_na(list(climate = "none", run = "historic run")) %>% 
  # Make factors
  mutate(sce = as.factor(sce), run = as.factor(run), sum_cur = 10*(sum_cur),
         climate = factor(climate, levels = c("none", "historic",
                                              "baseline", "RCP 8.5")),
         run = factor(run, levels = c("historic run", "BAU run", 
                                      "BAU run + corrs protection", "BAU run + ref", 
                                      "BAU run + corrs protection + ref",
                                      "BAU run + corrs protection + ref TARGETED")))
```

#### Set the ggplot theme

We see the ggplot theme to `theme_minimal()` and change the size of some plot elements.

```{r set_ggplot_theme}
theme_set(theme_minimal())
theme_update(legend.position = c(0.85, 0.20),
             #legend.justification = c(1, -0.2), # for inside plot
             #legend.position = "none",
             legend.box = "vertical",
             legend.background = element_blank(),
             legend.box.background = element_rect(colour = "black"),
             panel.border = element_rect(fill = NA),
             legend.title = element_text(size = 12),
             legend.text = element_text(size = 8),
             plot.title = element_text(size=22),
             plot.subtitle = element_text(size=22),
             axis.text.x = element_text(angle=65, vjust=0.6, size =15),
             axis.text.y = element_text(size =15),
             strip.text.x = element_text(size = 15),
             strip.text.y = element_text(size = 15),
             axis.title=element_text(size=18))
```

### Figures
#### Mean current flow change through time - historic

```{r fig_1_historic, message=FALSE, out.width="150%", fig.cap="Connectivity change for species through time, 1990-2010"}
fig_1_historic <- joined %>% 
  filter(climate == "none") %>% 
  group_by(scenarioId, species, iteration) %>% 
  group_modify(~mutate(.x , baseline = subset(.x, timestep == 1990)$sum_cur, 
                       the_diff = ((sum_cur-baseline)/baseline)*100 )) %>% 
  ggplot(aes(x=timestep, y=the_diff, col=source)) +
  scale_color_manual(values=c('#d8b365','#5ab4ac'), 
                     labels = c("Model", "Observation")) +
  geom_smooth(aes(group = sce), method = "glm", se=FALSE) +
  scale_linetype_manual(values = c(1,3,2,5))+
  geom_point(aes(group = sce)) +
  facet_wrap(~species, scales = "free") +
  labs(y = "Current flow (% Change)",
       x = "Year",
       col = "Source") +
  NULL
fig_1_historic
ggsave(fig_1_historic,
       filename = "outputs/figures/connectivity_decrease_x5species_historic.png",
       width = 17, height = 12)
```
##### Mean current flow change through time - chap 1

```{r figure_1_model, out.width="150%", fig.cap="Connectivity change for species through time, 2010-2100", message=FALSE}
fig_1_static <- joined %>% 
  filter(climate != "none", chapter %in% c("none", "chap_1")) %>% 
  group_by(scenarioId, species, iteration) %>% 
  group_modify(~mutate(.x , baseline = subset(.x, timestep == 2010)$sum_cur, 
                       the_diff = ((sum_cur-baseline)/baseline)*100 )) %>% 
  ggplot(aes(x=timestep, y=the_diff, col=climate)) +
  scale_color_manual(values=c('#ffe300', '#ff7a14', "#b31400"), 
                     labels = c("Historic", "Baseline", "RCP 8.5")) +
  geom_smooth(aes(group = sce, linetype=run), alpha=0.2, method="loess") +
  scale_linetype_discrete() +
  facet_wrap(~species, scales = "fixed") +
  geom_hline(yintercept = 0, linetype = "dashed", alpha = 0.5) +
  geom_vline(xintercept = 2020, linetype = "dashed", color = "darkGreen", alpha = 0.5) +
  labs(y = "Current flow (% Change)",
       x = "Year",
       col = "Climate",
       linetype = "Run") +
  guides(col = guide_legend(ncol = 2, nrow=2), 
         linetype = guide_legend(nrow=1, override.aes = list(colour = 'black'))) +
  theme(legend.position = c(0.85, 0.15))+
  NULL
fig_1_static
```

