#!/bin/sh
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_0_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/circuitscape_buffer -e y
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_0_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_0_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_0_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_0_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_0_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_0_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_0_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_0_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_0_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_0_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_1_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_1_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_1_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_1_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_1_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_1_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_1_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_1_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_1_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_1_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_2_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_2_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_2_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_2_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_2_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_2_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_2_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_2_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_2_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_2_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_3_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_3_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_3_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_3_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_3_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_3_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_3_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_3_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_3_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_3_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_4_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_4_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_4_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_4_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_4_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_4_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_4_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_4_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_4_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_4_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_5_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_5_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_5_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_5_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_5_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_5_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_5_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_5_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_1_ts_5_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_1_ts_5_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_0_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_0_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_0_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_0_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_0_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_0_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_0_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_0_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_0_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_0_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_1_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_1_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_1_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_1_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_1_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_1_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_1_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_1_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_1_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_1_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_2_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_2_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_2_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_2_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_2_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_2_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_2_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_2_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_2_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_2_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_3_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_3_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_3_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_3_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_3_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_3_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_3_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_3_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_3_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_3_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_4_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_4_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_4_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_4_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_4_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_4_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_4_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_4_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_4_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_4_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_5_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_5_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_5_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_5_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_5_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_5_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_5_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_5_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_10_it_2_ts_5_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_10_it_2_ts_5_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_0_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_0_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_0_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_0_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_0_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_0_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_0_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_0_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_0_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_0_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_1_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_1_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_1_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_1_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_1_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_1_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_1_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_1_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_1_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_1_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_2_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_2_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_2_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_2_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_2_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_2_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_2_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_2_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_2_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_2_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_3_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_3_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_3_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_3_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_3_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_3_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_3_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_3_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_3_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_3_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_4_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_4_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_4_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_4_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_4_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_4_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_4_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_4_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_4_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_4_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_5_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_5_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_5_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_5_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_5_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_5_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_5_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_5_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_1_ts_5_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_1_ts_5_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_0_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_0_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_0_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_0_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_0_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_0_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_0_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_0_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_0_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_0_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_1_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_1_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_1_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_1_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_1_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_1_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_1_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_1_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_1_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_1_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_2_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_2_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_2_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_2_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_2_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_2_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_2_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_2_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_2_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_2_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_3_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_3_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_3_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_3_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_3_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_3_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_3_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_3_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_3_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_3_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_4_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_4_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_4_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_4_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_4_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_4_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_4_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_4_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_4_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_4_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_5_BLBR_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_5_BLBR_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_5_MAAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_5_MAAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_5_PLCI_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_5_PLCI_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_5_RASY_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_5_RASY_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/sce_9_it_2_ts_5_URAM_.tif -b 90 -o outputs/reclassed_with_buffer/sce_9_it_2_ts_5_URAM_with_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/TRUE_lu_1_BLBR.tif -b 90 -o outputs/reclassed_with_buffer/TRUE_lu_1_BLBRwith_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/TRUE_lu_1_MAAM.tif -b 90 -o outputs/reclassed_with_buffer/TRUE_lu_1_MAAMwith_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/TRUE_lu_1_PLCI.tif -b 90 -o outputs/reclassed_with_buffer/TRUE_lu_1_PLCIwith_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/TRUE_lu_1_RASY.tif -b 90 -o outputs/reclassed_with_buffer/TRUE_lu_1_RASYwith_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/TRUE_lu_1_URAM.tif -b 90 -o outputs/reclassed_with_buffer/TRUE_lu_1_URAMwith_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/TRUE_lu_2_BLBR.tif -b 90 -o outputs/reclassed_with_buffer/TRUE_lu_2_BLBRwith_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/TRUE_lu_2_MAAM.tif -b 90 -o outputs/reclassed_with_buffer/TRUE_lu_2_MAAMwith_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/TRUE_lu_2_PLCI.tif -b 90 -o outputs/reclassed_with_buffer/TRUE_lu_2_PLCIwith_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/TRUE_lu_2_RASY.tif -b 90 -o outputs/reclassed_with_buffer/TRUE_lu_2_RASYwith_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/TRUE_lu_2_URAM.tif -b 90 -o outputs/reclassed_with_buffer/TRUE_lu_2_URAMwith_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/TRUE_lu_3_BLBR.tif -b 90 -o outputs/reclassed_with_buffer/TRUE_lu_3_BLBRwith_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/TRUE_lu_3_MAAM.tif -b 90 -o outputs/reclassed_with_buffer/TRUE_lu_3_MAAMwith_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/TRUE_lu_3_PLCI.tif -b 90 -o outputs/reclassed_with_buffer/TRUE_lu_3_PLCIwith_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/TRUE_lu_3_RASY.tif -b 90 -o outputs/reclassed_with_buffer/TRUE_lu_3_RASYwith_buffer -e n
sh scripts/0.1_add_buffer_lowlands_modified.sh -i outputs/reclassed/TRUE_lu_3_URAM.tif -b 90 -o outputs/reclassed_with_buffer/TRUE_lu_3_URAMwith_buffer -e n
