# This is a basic workflow to help you get started with Actions

name: Build / Push Docker image

on:
  push:
    branches: [ master ]
    paths: 
      - "Dockerfiles/Dockerfile"
      - ".github/workflows/build_and_push.yml"
      - "renv.lock"
  schedule:
    - cron: "0 1 * * *"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        with:
          repository: vlucet/land_con_monteregie
          dockerfile: Dockerfiles/Dockerfile 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 3.6.2-1

