# This is a basic workflow to help you get started with Actions

name: Build / push Docker image

on:
  push:
    branches: [ master ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:

      - uses: docker/build-push-action@v1
        with:
          path: Dockerfiles
          dockerfile: Dockerfiles/Dockerfile 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: vlucet/land_con_monteregie
          tags: 3.6.2-1

