# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
    #paths:
    #  - ".github/workflows/knit.yml"
  schedule: # Runs at 06:00 UTC every day
    - cron: "0 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: pull docker image
      run: docker pull vlucet/land_con_monteregie:3.6.2-1 
      
    - name: knit rmd
      run: docker run -e DISABLE_AUTH=true vlucet/land_con_monteregie:3.6.2-1 git pull && /bin/bash landcon.sh -g
    
    - name: push changes
      run: | 
          git add docs/** \\
          git commit -m "CI gh page" 
          git push
