# This is a basic workflow to help you get started with Actions

name: CI - All Figures

on:
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/knit.yml"
      - "thesis/**"
  schedule: # Runs at 06:00 UTC every day
    - cron: "0 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    
    # - name: test
    #   run: pwd && ls

    - name: pull docker image
      run: docker pull vlucet/land_con_monteregie:3.6.2-1 
      
    - name: knit rmd
      run: |
        docker run -e BIG_FIGS='FALSE' -v "$(pwd)/docs/:/home/rstudio/land_con_monteregie/docs/" \
        vlucet/land_con_monteregie:3.6.2-1 /bin/bash -c "git checkout * && git pull && git lfs fetch && git lfs checkout && ./landcon.sh -g"
    
    - name: check for changes
      uses: UnicornGlobal/has-changes-action@v1.0.11
    
    - name: Commit files
      if: steps.changes.outputs.changed == 1
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/**
        git commit -m "CI - figures"

    - name: Push changes
      if: steps.changes.outputs.changed == 1
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
