# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/knit.yml"
  schedule: # Runs at 01:00 UTC every day
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: pull docker image
      run: docker pull vlucet/land_con_monteregie:3.6.2-1 
      
    - name: knit rmd
      run: ./landcon.sh -g

    # Runs a set of commands using the runners shell
    #- name: Run a multi-line script
    #  run: |
    #    echo Add other actions to build,
    #    echo test, and deploy your project.
